/* 
  Sketch generated by the Arduino IoT Cloud Thing "Untitled 2"
  https://create.arduino.cc/cloud/things/4116fe99-067a-4b60-aab1-c2ae4086d100 

  Arduino IoT Cloud Variables description

  The following variables are automatically generated and updated when changes are made to the Thing

  float battery_charge;
  float battery_charge_rate;
  float battery_voltage;
  bool battery_connected;
  bool stay_awake_for_update;

  Variables which are marked as READ/WRITE in the Cloud Thing will also have functions
  which are called when their values are changed from the Dashboard.
  These functions are generated with the Thing and added at the end of this sketch.
*/

#include "arduino_secrets.h"
#include "thingProperties.h"
#include "Adafruit_MAX1704X.h"
#include <WiFi.h>
#include <Wire.h>

#define DEBUG_SERIAL 0

Adafruit_MAX17048 maxlipo;

const uint64_t SLEEP_INTERVAL_US = 3ULL * 60ULL * 1000000ULL;
const uint32_t CLOUD_AWAKE_WINDOW_MS = 15000UL;
const uint32_t CLOUD_UPDATE_STEP_MS = 100UL;
const uint32_t BATTERY_RETRY_DELAY_MS = 250UL;
const uint8_t BATTERY_INIT_RETRIES = 5;
const uint8_t BATTERY_READ_RETRIES = 5;
const uint32_t STAY_AWAKE_SAMPLE_PERIOD_MS = 30000UL;
const float MIN_VALID_BATTERY_VOLTAGE = 2.5f;

void disableBoardPowerDraw() {
  pinMode(NEOPIXEL_POWER, OUTPUT);
  digitalWrite(NEOPIXEL_POWER, LOW);

  pinMode(LED_BUILTIN, OUTPUT);
  digitalWrite(LED_BUILTIN, LOW);
}

bool initBatteryMonitor() {
  for (uint8_t attempt = 0; attempt < BATTERY_INIT_RETRIES; ++attempt) {
    if (maxlipo.begin()) {
      battery_connected = true;
      maxlipo.setAlertVoltages(2.0, 4.2);
      return true;
    }

    delay(BATTERY_RETRY_DELAY_MS);
  }

  battery_connected = false;
  battery_voltage = -1.0f;
  battery_charge = -1.0f;
  battery_charge_rate = 0.0f;
  return false;
}

void readBatteryState() {
  if (!battery_connected) {
    return;
  }

  for (uint8_t attempt = 0; attempt < BATTERY_READ_RETRIES; ++attempt) {
    const float cellVoltage = maxlipo.cellVoltage();
    const float cellPercent = maxlipo.cellPercent();
    const float chargeRate = maxlipo.chargeRate();

    const bool validVoltage = !isnan(cellVoltage) && cellVoltage >= MIN_VALID_BATTERY_VOLTAGE;
    const bool validPercent = !isnan(cellPercent) && cellPercent >= 0.0f;

    if (validVoltage && validPercent) {
      battery_connected = true;
      battery_voltage = cellVoltage;
      battery_charge = cellPercent;
      battery_charge_rate = isnan(chargeRate) ? 0.0f : chargeRate;
      return;
    }

    delay(BATTERY_RETRY_DELAY_MS);
  }

  battery_connected = false;
  battery_voltage = -1.0f;
  battery_charge = -1.0f;
  battery_charge_rate = 0.0f;
}

void publishToCloud() {
  ArduinoCloud.begin(ArduinoIoTPreferredConnection);
  setDebugMessageLevel(DEBUG_SERIAL ? 2 : 0);

#if DEBUG_SERIAL
  ArduinoCloud.printDebugInfo();
#endif

  const uint32_t wakeStartMs = millis();
  while (millis() - wakeStartMs < CLOUD_AWAKE_WINDOW_MS) {
    ArduinoCloud.update();
    delay(CLOUD_UPDATE_STEP_MS);

    if (stay_awake_for_update) {
      return;
    }
  }
}

void stayAwakeMode() {
  uint32_t lastBatterySampleMs = 0;

  while (stay_awake_for_update) {
    const uint32_t nowMs = millis();
    if (nowMs - lastBatterySampleMs >= STAY_AWAKE_SAMPLE_PERIOD_MS) {
      readBatteryState();
      lastBatterySampleMs = nowMs;
    }

    ArduinoCloud.update();
    delay(CLOUD_UPDATE_STEP_MS);
  }
}

void enterDeepSleep() {
  WiFi.disconnect(true);
  WiFi.mode(WIFI_OFF);
  delay(20);

  esp_sleep_enable_timer_wakeup(SLEEP_INTERVAL_US);
  esp_deep_sleep_start();
}

void setup() {
#if DEBUG_SERIAL
  Serial.begin(115200);
  delay(1500);
#endif

  disableBoardPowerDraw();
  Wire.begin();
  delay(BATTERY_RETRY_DELAY_MS);

  // Defined in thingProperties.h
  initProperties();
  initBatteryMonitor();
  readBatteryState();
  publishToCloud();

  if (stay_awake_for_update) {
    stayAwakeMode();
  }

  enterDeepSleep();
}

void loop() {}

void onStayAwakeForUpdateChange() {
#if DEBUG_SERIAL
  Serial.print("stay_awake_for_update = ");
  Serial.println(stay_awake_for_update ? "true" : "false");
#endif
}