/* 
  Sketch generated by the Arduino IoT Cloud Thing "Untitled 2"
  https://create.arduino.cc/cloud/things/4116fe99-067a-4b60-aab1-c2ae4086d100 

  Arduino IoT Cloud Variables description

  The following variables are automatically generated and updated when changes are made to the Thing

  float battery_charge;
  float battery_charge_rate;
  float battery_voltage;
  bool battery_connected;

  Variables which are marked as READ/WRITE in the Cloud Thing will also have functions
  which are called when their values are changed from the Dashboard.
  These functions are generated with the Thing and added at the end of this sketch.
*/

#include "thingProperties.h"
#include "Adafruit_MAX1704X.h"

Adafruit_MAX17048 maxlipo;

void setup() {
  // Initialize serial and wait for port to open:
  Serial.begin(115200);
  // This delay gives the chance to wait for a Serial Monitor without blocking if none is found
  delay(1500); 

  // Defined in thingProperties.h
  initProperties();

  // Connect to Arduino IoT Cloud
  ArduinoCloud.begin(ArduinoIoTPreferredConnection);
  
  /*
     The following function allows you to obtain more information
     related to the state of network and IoT Cloud connection and errors
     the higher number the more granular information you’ll get.
     The default is 0 (only errors).
     Maximum is 4
 */
  setDebugMessageLevel(2);
  ArduinoCloud.printDebugInfo();

  // disable NEOPIXEL to reduce power usage
  pinMode(NEOPIXEL_POWER, OUTPUT);
  digitalWrite(NEOPIXEL_POWER, LOW);
  
  // Set up LED to blink
  pinMode(LED_BUILTIN, OUTPUT);

  // Battery Monitor Setup
  Serial.println(F("\nAdafruit MAX17048 advanced demo"));

  const int MAX_BATT_CHECKS = 10;
  int batt_checks = 0;
  bool found_battery = true;
  while (!maxlipo.begin()) {
    Serial.println(F("Couldnt find Adafruit MAX17048?\nMake sure a battery is plugged in!"));
    batt_checks++;
    if (batt_checks >= 10)
    {
      found_battery = false;
      break;
    }
    delay(2000);
  }
  battery_connected = found_battery;
  
  if (found_battery)
  {
    Serial.print(F("Found MAX17048"));
    Serial.print(F(" with Chip ID: 0x")); 
    Serial.println(maxlipo.getChipID(), HEX);

    // Quick starting allows an instant 'auto-calibration' of the battery. However, its a bad idea
    // to do this right when the battery is first plugged in or if there's a lot of load on the battery
    // so uncomment only if you're sure you want to 'reset' the chips charge calculator.
    // Serial.println("Quick starting");
    // maxlipo.quickStart();
    
    // The reset voltage is what the chip considers 'battery has been removed and replaced'
    // The default is 3.0 Volts but you can change it here: 
    //maxlipo.setResetVoltage(2.5);
    Serial.print(F("Reset voltage = ")); 
    Serial.print(maxlipo.getResetVoltage());
    Serial.println(" V");
  
    // Hibernation mode reduces how often the ADC is read, for power reduction. There is an automatic
    // enter/exit mode but you can also customize the activity threshold both as voltage and charge rate
  
    //maxlipo.setActivityThreshold(0.15);
    Serial.print(F("Activity threshold = ")); 
    Serial.print(maxlipo.getActivityThreshold()); 
    Serial.println(" V change");
  
    //maxlipo.setHibernationThreshold(5);
    Serial.print(F("Hibernation threshold = "));
    Serial.print(maxlipo.getHibernationThreshold()); 
    Serial.println(" %/hour");
  
    // You can also 'force' hibernation mode!
    // maxlipo.hibernate();
    // ...or force it to wake up!
    // maxlipo.wake();
  
    // The alert pin can be used to detect when the voltage of the battery goes below or
    // above a voltage, you can also query the alert in the loop.
    maxlipo.setAlertVoltages(2.0, 4.2);
  
    float alert_min, alert_max;
    maxlipo.getAlertVoltages(alert_min, alert_max);
    Serial.print("Alert voltages: "); 
    Serial.print(alert_min); Serial.print(" ~ "); 
    Serial.print(alert_max); Serial.println(" V");
  }
  else
  {
    Serial.println("No battery found! Giving up");
  }
}

bool led_state = false;
uint64_t last_change_time_ms = 0ULL;
const uint64_t BLINK_TIME_MS = 300ULL;

uint64_t last_batt_read_time_ms = 0ULL;
const uint64_t BATT_READ_PERIOD_MS = 2000ULL;

void loop() {
  ArduinoCloud.update();
  
  // Your code here 
  uint64_t time_now_ms = millis();

  if (time_now_ms - last_change_time_ms >= BLINK_TIME_MS)
  {
    digitalWrite(LED_BUILTIN, (led_state ? LOW : HIGH));
    led_state = !led_state;
    last_change_time_ms = time_now_ms;
  }

  // Battery Checking
  if (battery_connected && (time_now_ms - last_batt_read_time_ms > BATT_READ_PERIOD_MS))
  {
    last_batt_read_time_ms = time_now_ms;
    float cellVoltage = maxlipo.cellVoltage();
    if (isnan(cellVoltage)) {
      Serial.println("Failed to read cell voltage, check battery is connected!");
      cellVoltage = -1.0;
      battery_connected = false;
      return;
    }
    else
    {
      battery_connected = true;
    }

    battery_voltage = cellVoltage;
    battery_charge = maxlipo.cellPercent();
    battery_charge_rate = maxlipo.chargeRate();
    // Serial.print(F("Batt Voltage: ")); Serial.print(cellVoltage, 3); Serial.println(" V");
    // Serial.print(F("Batt Percent: ")); Serial.print(battery_charge, 1); Serial.println(" %");
    // Serial.print(F("(Dis)Charge rate : ")); Serial.print(battery_charge_rate, 1); Serial.println(" %/hr");
  
    // we can check if we're hibernating or not
    // if (maxlipo.isHibernating()) {
    //   Serial.println(F("Hibernating!"));
    // }
  
  
    // if (maxlipo.isActiveAlert()) {
    //   uint8_t status_flags = maxlipo.getAlertStatus();
    //   Serial.print(F("ALERT! flags = 0x"));
    //   Serial.print(status_flags, HEX);
      
    //   if (status_flags & MAX1704X_ALERTFLAG_SOC_CHANGE) {
    //     Serial.print(", SOC Change");
    //     maxlipo.clearAlertFlag(MAX1704X_ALERTFLAG_SOC_CHANGE); // clear the alert
    //   }
    //   if (status_flags & MAX1704X_ALERTFLAG_SOC_LOW) {
    //     Serial.print(", SOC Low");
    //     maxlipo.clearAlertFlag(MAX1704X_ALERTFLAG_SOC_LOW); // clear the alert
    //   }
    //   if (status_flags & MAX1704X_ALERTFLAG_VOLTAGE_RESET) {
    //     Serial.print(", Voltage reset");
    //     maxlipo.clearAlertFlag(MAX1704X_ALERTFLAG_VOLTAGE_RESET); // clear the alert
    //   }
    //   if (status_flags & MAX1704X_ALERTFLAG_VOLTAGE_LOW) {
    //     Serial.print(", Voltage low");
    //     maxlipo.clearAlertFlag(MAX1704X_ALERTFLAG_VOLTAGE_LOW); // clear the alert
    //   }
    //   if (status_flags & MAX1704X_ALERTFLAG_VOLTAGE_HIGH) {
    //     Serial.print(", Voltage high");
    //     maxlipo.clearAlertFlag(MAX1704X_ALERTFLAG_VOLTAGE_HIGH); // clear the alert
    //   }
    //   if (status_flags & MAX1704X_ALERTFLAG_RESET_INDICATOR) {
    //     Serial.print(", Reset Indicator");
    //     maxlipo.clearAlertFlag(MAX1704X_ALERTFLAG_RESET_INDICATOR); // clear the alert
    //   }
    //   Serial.println();
    // }
    // Serial.println();
    // Serial.println();
  }
  
}











