#include <CHT832X.h>
#include <Adafruit_HX711.h>
/* 
  Sketch generated by the Arduino IoT Cloud Thing "Untitled 2"
  https://create.arduino.cc/cloud/things/4116fe99-067a-4b60-aab1-c2ae4086d100 

  Arduino IoT Cloud Variables description

  The following variables are automatically generated and updated when changes are made to the Thing

  float battery_charge;
  float battery_voltage;
  float cal_weight_lbs;
  float humidity_pct;
  float temp_f;
  float weight_lbs;
  int raw_scale_counts;
  bool calibrate_now;
  bool stay_awake_for_update;
  bool tare;

  Variables which are marked as READ/WRITE in the Cloud Thing will also have functions
  which are called when their values are changed from the Dashboard.
  These functions are generated with the Thing and added at the end of this sketch.
*/

#include "arduino_secrets.h"
#include "thingProperties.h"
#include "Adafruit_MAX1704X.h"
#include <Preferences.h>
#include <WiFi.h>
#include <Wire.h>

#define DEBUG_SERIAL 0

Adafruit_MAX17048 maxlipo;
CHT832X envSensor;
const uint8_t HX711_DOUT_PIN = 5;
const uint8_t HX711_SCK_PIN = 9;
Adafruit_HX711 scale(HX711_DOUT_PIN, HX711_SCK_PIN);
Preferences prefs;

const uint64_t SLEEP_INTERVAL_US = 5ULL * 60ULL * 1000000ULL;
const uint32_t CLOUD_AWAKE_WINDOW_MS = 20000UL;
const uint32_t CLOUD_UPDATE_STEP_MS = 100UL;
const uint32_t BATTERY_RETRY_DELAY_MS = 250UL;
const uint8_t BATTERY_INIT_RETRIES = 5;
const uint8_t BATTERY_READ_RETRIES = 5;
const uint32_t STAY_AWAKE_SAMPLE_PERIOD_MS = 30000UL;
const float MIN_VALID_BATTERY_VOLTAGE = 2.5f;
const uint32_t SCALE_SAMPLE_PERIOD_MS = 10000UL;
const uint32_t HX711_READY_TIMEOUT_MS = 1000UL;
const uint8_t SCALE_READ_RETRIES = 3;
const uint32_t SCALE_READ_RETRY_DELAY_MS = 150UL;
const uint8_t SCALE_AVG_SAMPLES = 50;
const float SCALE_MIN_FACTOR_ABS = 0.0001f;
const float SCALE_NEAR_ZERO_LBS = 0.5f;
const float WEIGHT_INVALID_CALIBRATION_SENTINEL_LBS = -1234.5f;
const float WEIGHT_READ_FAILED_SENTINEL_LBS = -2234.5f;
const int32_t RAW_SCALE_READ_FAILED_SENTINEL_COUNTS = -2147483000;
const float TEMP_SENSOR_NOT_CONNECTED_SENTINEL_F = -999.0f;
const float HUMIDITY_SENSOR_NOT_CONNECTED_SENTINEL_PCT = -1.0f;

const char* SCALE_PREFS_NAMESPACE = "hx711";
const char* SCALE_PREF_OFFSET_KEY = "offset";
const char* SCALE_PREF_FACTOR_KEY = "factor";

int32_t scaleOffsetCounts = 0;
float scaleCountsPerLb = 0.0f;
bool scaleInitialized = false;
bool batteryMonitorInitialized = false;
bool envSensorInitialized = false;

bool isScaleCalibrated_() {
  return !isnan(scaleCountsPerLb) && fabs(scaleCountsPerLb) >= SCALE_MIN_FACTOR_ABS;
}

void loadScaleCalibration_() {
  if (!prefs.begin(SCALE_PREFS_NAMESPACE, true)) return;
  scaleOffsetCounts = prefs.getInt(SCALE_PREF_OFFSET_KEY, 0);
  scaleCountsPerLb = prefs.getFloat(SCALE_PREF_FACTOR_KEY, 0.0f);
  prefs.end();
}

void saveScaleCalibration_() {
  if (!prefs.begin(SCALE_PREFS_NAMESPACE, false)) return;
  prefs.putInt(SCALE_PREF_OFFSET_KEY, scaleOffsetCounts);
  prefs.putFloat(SCALE_PREF_FACTOR_KEY, scaleCountsPerLb);
  prefs.end();
}

bool waitForScaleReady_(uint32_t timeoutMs) {
  const uint32_t startMs = millis();
  while (scale.isBusy()) {
    if (millis() - startMs >= timeoutMs) return false;
    delay(1);
  }
  return true;
}

bool readScaleRawAverage_(int32_t &outCounts) {
  if (!scaleInitialized) return false;

  int64_t sum = 0;
  uint8_t samples = 0;
  while (samples < SCALE_AVG_SAMPLES) {
    if (!waitForScaleReady_(HX711_READY_TIMEOUT_MS)) {
      return false;
    }
    sum += scale.readChannelRaw(CHAN_A_GAIN_64);
    samples++;
  }

  outCounts = static_cast<int32_t>(sum / SCALE_AVG_SAMPLES);
  return true;
}

bool readScaleRawAverageWithRetries_(int32_t &outCounts) {
  for (uint8_t attempt = 0; attempt < SCALE_READ_RETRIES; ++attempt) {
    if (readScaleRawAverage_(outCounts)) {
      return true;
    }
    delay(SCALE_READ_RETRY_DELAY_MS);
  }
  return false;
}

void markScaleReadFailed_() {
  raw_scale_counts = RAW_SCALE_READ_FAILED_SENTINEL_COUNTS;
  weight_lbs = WEIGHT_READ_FAILED_SENTINEL_LBS;
}

void markEnvSensorDisconnected_() {
  temp_f = TEMP_SENSOR_NOT_CONNECTED_SENTINEL_F;
  humidity_pct = HUMIDITY_SENSOR_NOT_CONNECTED_SENTINEL_PCT;
}

bool initEnvSensor_() {
  const int status = envSensor.begin();
  envSensorInitialized = (status == CHT832X_OK) && envSensor.isConnected();
  if (!envSensorInitialized) {
    markEnvSensorDisconnected_();
    return false;
  }
  return true;
}

bool readEnvSensor_() {
  if (!envSensorInitialized && !initEnvSensor_()) {
    markEnvSensorDisconnected_();
    return false;
  }

  if (!envSensor.isConnected()) {
    envSensorInitialized = false;
    markEnvSensorDisconnected_();
    return false;
  }

  const int status = envSensor.read();
  if (status != CHT832X_OK) {
    markEnvSensorDisconnected_();
    return false;
  }

  const float tempC = envSensor.getTemperature();
  const float hum = envSensor.getHumidity();
  if (!isnan(tempC) && !isnan(hum)) {
    temp_f = (tempC * 9.0f / 5.0f) + 32.0f;
    humidity_pct = hum;
    return true;
  }

  markEnvSensorDisconnected_();
  return false;
}

bool initScale_() {
  scale.begin();
#if DEBUG_SERIAL
  Serial.println("HX711 scale.begin() called");
#endif
  scaleInitialized = true;

  // Prime a couple reads so first published value is less noisy.
  int32_t throwaway = 0;
  const bool prime1 = readScaleRawAverageWithRetries_(throwaway);
#if DEBUG_SERIAL
  Serial.print("HX711 prime read #1 ok: ");
  Serial.print(prime1 ? "true" : "false");
  if (prime1) {
    Serial.print(", raw=");
    Serial.println(throwaway);
  } else {
    Serial.println();
  }
#endif

  const bool prime2 = readScaleRawAverageWithRetries_(throwaway);
#if DEBUG_SERIAL
  Serial.print("HX711 prime read #2 ok: ");
  Serial.print(prime2 ? "true" : "false");
  if (prime2) {
    Serial.print(", raw=");
    Serial.println(throwaway);
  } else {
    Serial.println();
  }
#endif
  return true;
}

bool refreshWeightReading_() {
  int32_t raw = 0;
  if (!readScaleRawAverageWithRetries_(raw)) {
    markScaleReadFailed_();
    return false;
  }

  raw_scale_counts = raw;

  if (!isScaleCalibrated_()) {
    weight_lbs = WEIGHT_INVALID_CALIBRATION_SENTINEL_LBS;
    return true;
  }

  const float pounds = (static_cast<float>(raw - scaleOffsetCounts)) / scaleCountsPerLb;
  weight_lbs = fabs(pounds) < SCALE_NEAR_ZERO_LBS ? 0.0f : pounds;
  return true;
}

bool tareScale_() {
  int32_t raw = 0;
  if (!readScaleRawAverageWithRetries_(raw)) return false;
  scaleOffsetCounts = raw;
  saveScaleCalibration_();
  return refreshWeightReading_();
}

bool calibrateScaleFromKnownWeight_() {
  if (cal_weight_lbs <= 0.0f) return false;

  int32_t raw = 0;
  if (!readScaleRawAverageWithRetries_(raw)) return false;

  const int32_t deltaCounts = raw - scaleOffsetCounts;
  if (deltaCounts == 0) return false;

  scaleCountsPerLb = static_cast<float>(deltaCounts) / cal_weight_lbs;
  if (!isScaleCalibrated_()) return false;

  saveScaleCalibration_();
  return refreshWeightReading_();
}

void disableBoardPowerDraw() {
  pinMode(NEOPIXEL_POWER, OUTPUT);
  digitalWrite(NEOPIXEL_POWER, LOW);

  pinMode(LED_BUILTIN, OUTPUT);
  digitalWrite(LED_BUILTIN, LOW);
}

bool initBatteryMonitor() {
  for (uint8_t attempt = 0; attempt < BATTERY_INIT_RETRIES; ++attempt) {
    if (maxlipo.begin()) {
      batteryMonitorInitialized = true;
      maxlipo.setAlertVoltages(2.0, 4.2);
      return true;
    }

    delay(BATTERY_RETRY_DELAY_MS);
  }

  batteryMonitorInitialized = false;
  battery_voltage = -1.0f;
  battery_charge = -1.0f;
  return false;
}

void readBatteryState() {
  if (!batteryMonitorInitialized && !initBatteryMonitor()) {
    battery_voltage = -1.0f;
    battery_charge = -1.0f;
    return;
  }

  for (uint8_t attempt = 0; attempt < BATTERY_READ_RETRIES; ++attempt) {
    const float cellVoltage = maxlipo.cellVoltage();
    const float cellPercent = maxlipo.cellPercent();

    const bool validVoltage = !isnan(cellVoltage) && cellVoltage >= MIN_VALID_BATTERY_VOLTAGE;
    const bool validPercent = !isnan(cellPercent) && cellPercent >= 0.0f;

    if (validVoltage && validPercent) {
      battery_voltage = cellVoltage;
      battery_charge = cellPercent;
      return;
    }

    delay(BATTERY_RETRY_DELAY_MS);
  }

  battery_voltage = -1.0f;
  battery_charge = -1.0f;
}

void publishToCloud() {
  ArduinoCloud.begin(ArduinoIoTPreferredConnection);
  setDebugMessageLevel(DEBUG_SERIAL ? 2 : 0);

#if DEBUG_SERIAL
  ArduinoCloud.printDebugInfo();
#endif

  const uint32_t wakeStartMs = millis();
  while (millis() - wakeStartMs < CLOUD_AWAKE_WINDOW_MS) {
    ArduinoCloud.update();
    delay(CLOUD_UPDATE_STEP_MS);

    if (stay_awake_for_update) {
      return;
    }
  }
}

void stayAwakeMode() {
  uint32_t lastBatterySampleMs = 0;
  uint32_t lastScaleSampleMs = 0;

  while (stay_awake_for_update) {
    const uint32_t nowMs = millis();
    if (nowMs - lastBatterySampleMs >= STAY_AWAKE_SAMPLE_PERIOD_MS) {
      readBatteryState();
      lastBatterySampleMs = nowMs;
    }

    if (nowMs - lastScaleSampleMs >= SCALE_SAMPLE_PERIOD_MS) {
      refreshWeightReading_();
      readEnvSensor_();
      lastScaleSampleMs = nowMs;
    }

    ArduinoCloud.update();
    delay(CLOUD_UPDATE_STEP_MS);
  }
}

void enterDeepSleep() {
  // HX711 enters low-power mode when PD_SCK is held HIGH for >60 us.
  pinMode(HX711_SCK_PIN, OUTPUT);
  digitalWrite(HX711_SCK_PIN, HIGH);
  delayMicroseconds(80);

  WiFi.disconnect(true);
  WiFi.mode(WIFI_OFF);
  delay(20);

  esp_sleep_enable_timer_wakeup(SLEEP_INTERVAL_US);
  esp_deep_sleep_start();
}

void setup() {
#if DEBUG_SERIAL
  Serial.begin(115200);
  delay(10000);
#endif

  disableBoardPowerDraw();
  Wire.begin();
  delay(BATTERY_RETRY_DELAY_MS);

  // Defined in thingProperties.h
  initProperties();

  // Initialize to explicit read-failure sentinels until a valid sample arrives.
  markScaleReadFailed_();
  markEnvSensorDisconnected_();

  cal_weight_lbs = cal_weight_lbs > 0.0f ? cal_weight_lbs : 10.0f;
  calibrate_now = false;
  tare = false;

  initBatteryMonitor();
  loadScaleCalibration_();
  initScale_();
  initEnvSensor_();
  readBatteryState();
  refreshWeightReading_();
  readEnvSensor_();
  publishToCloud();

  if (stay_awake_for_update) {
    stayAwakeMode();
  }

  enterDeepSleep();
}

void loop() {}

void onStayAwakeForUpdateChange() {
#if DEBUG_SERIAL
  Serial.print("stay_awake_for_update = ");
  Serial.println(stay_awake_for_update ? "true" : "false");
#endif
}

/*
  Since Tare is READ_WRITE variable, onTareChange() is
  executed every time a new value is received from IoT Cloud.
*/
void onTareChange()  {
  if (!tare) return;
  tareScale_();
  tare = false;
}

/*
  Since CalWeightLbs is READ_WRITE variable, onCalWeightLbsChange() is
  executed every time a new value is received from IoT Cloud.
*/
void onCalWeightLbsChange()  {
  if (cal_weight_lbs < 0.0f) {
    cal_weight_lbs = 0.0f;
  }
}

/*
  Since CalibrateNow is READ_WRITE variable, onCalibrateNowChange() is
  executed every time a new value is received from IoT Cloud.
*/
void onCalibrateNowChange()  {
  if (!calibrate_now) return;
  calibrateScaleFromKnownWeight_();
  calibrate_now = false;
}
