// Code generated by Arduino IoT Cloud, DO NOT EDIT.

#include <ArduinoIoTCloud.h>
#include <Arduino_ConnectionHandler.h>

const char DEVICE_LOGIN_NAME[]  = "1e432d9f-0798-4578-9da1-31471c5ba848";

const char SSID[]               = SECRET_SSID;    // Network SSID (name)
const char PASS[]               = SECRET_OPTIONAL_PASS;    // Network password (use for WPA, or use as key for WEP)
const char DEVICE_KEY[]  = SECRET_DEVICE_KEY;    // Secret device password


float battery_charge;
float battery_charge_rate;
float battery_voltage;
bool battery_connected;

void initProperties(){

  ArduinoCloud.setBoardId(DEVICE_LOGIN_NAME);
  ArduinoCloud.setSecretDeviceKey(DEVICE_KEY);
  ArduinoCloud.addProperty(battery_charge, READ, 60 * SECONDS, NULL);
  ArduinoCloud.addProperty(battery_charge_rate, READ, 60 * SECONDS, NULL);
  ArduinoCloud.addProperty(battery_voltage, READ, 60 * SECONDS, NULL);
  ArduinoCloud.addProperty(battery_connected, READ, 60 * SECONDS, NULL);

}

WiFiConnectionHandler ArduinoIoTPreferredConnection(SSID, PASS);
